/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import laya.ui.View;
	import laya.webgl.WebGL;
	import ui.Cz_xx_chooseMoneyUI;
	import ui.Cz_xx_ewmUI;
	import ui.Cz_xx_BankUI;
	import laya.display.Text;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 1280;
		public static var height:int = 720;
		public static var scaleMode:String = "fixedauto";
		public static var screenMode:String = "horizontal";
		public static var alignV:String = "middle";
		public static var alignH:String = "center";
		public static var startScene:* = "ChongZhiUi.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = false;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("ui.Cz_xx_chooseMoneyUI",Cz_xx_chooseMoneyUI);
			reg("ui.Cz_xx_ewmUI",Cz_xx_ewmUI);
			reg("ui.Cz_xx_BankUI",Cz_xx_BankUI);
			reg("laya.display.Text",Text);
		}
		GameConfig.init();
	}
}